name: PyStand packing

on:
  push:

jobs:
  task:
    runs-on: windows-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip -OutFile runtime.zip
          unzip runtime -d runtime
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t site-packages

      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: richi-console-${{ github.sha }}
          path: |
            bin
            conf
            src
            runtime
            site-packages
            richi-console*

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      #     file: soul-helper
      #     asset_name: soul-helper-windows-amd64
      #     tag: ${{ github.ref }}
      #     overwrite: true