name: PyStand Packing

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip -OutFile runtime.zip
          unzip runtime.zip -d runtime
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t site-packages

      - name: Create archives
        run: 7z a richi-console-v${{ github.ref_name }}.zip bin conf src runtime site-packages richi-console*

      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          path: richi-console-v${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: richi-console-v${{ github.ref_name }}.zip
