name: Pyinstaller packing

on:
  push:

jobs:
  task:
    runs-on: windows-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Packing
        run: |
          pyinstaller -y main.spec
          mv dist soul-helper
          cp -r bin soul-helper/
          cp -r src soul-helper/

      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: Development-${{ github.sha }}
          path: soul-helper

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      #     file: soul-helper
      #     asset_name: soul-helper-windows-amd64
      #     tag: ${{ github.ref }}
      #     overwrite: true