name: Pyinstaller Packing

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pack:
    runs-on: windows-latest
    env:
      PROXINJECT: https://github.com/PragmaTwice/proxinject/releases/download/v0.5.0-pre/proxinject-v0.5.0-pre-x64.zip
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Pack mhmp
        run: |
          python -m pip install .[pack]
          pyinstaller --clean mhmp.spec
          ####
          curl ${{ env.PROXINJECT }} -Lo proxinject.zip
          unzip proxinject.zip
          mv release dist/mhmp/proxinject
          7z a mhmp-${{ github.ref_name }}-win64.7z ./dist/mhmp/

      - uses: actions/upload-artifact@v4
        with:
          name: mhmp-${{ github.sha }}
          path: dist/mhmp

      - if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT }}
          files: mhmp-${{ github.ref_name }}-win64.7z
