name: Pyinstaller Packing

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: PragmaTwice/proxinject
          fetch-depth: 0

      - name: Build proxinject
        run: |
          ./build.ps1 -mode Release -arch x64

      - uses: actions/upload-artifact@v4
        with:
          name: proxinject-${{ github.sha }}
          path: release

  pack:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: actions/download-artifact@v4
        with:
          path: proxinject
          merge-multiple: true

      - name: Pack mhmp
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
          pyinstaller --clean mhmp.spec
          ####
          mv proxinject dist/mhmp/
          7z a mhmp-${{ github.ref_name }}-win64.7z ./dist/mhmp/

      - uses: actions/upload-artifact@v4
        with:
          name: mhmp-${{ github.sha }}
          path: dist/mhmp

      - if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT }}
          files: mhmp-${{ github.ref_name }}-win64.7z
