name: Embed Python Packing

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure embed python
        run: |
          #### Init embed python
          curl https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip -o embed.zip
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          unzip embed.zip -d embed
          embed\python get-pip.py

          #### Install dependencies
          echo "import site" >> embed\python310._pth
          echo ".." >> embed\python310._pth
          embed\python -m pip install -r requirements.txt

      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: development-${{ github.sha }}
          path: embed utils mhm mhm.cmd

      - name: Create archives
        if: startsWith(github.ref, 'refs/tags/')
        run: 7z a mhm-${{ github.ref_name }}-win64.7z embed utils mhm mhm.cmd

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: mhm-${{ github.ref_name }}-win64.7z
