name: Pyinstaller Packing

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - id: cache-proxinject
        uses: actions/cache@v4
        with:
          path: proxinject.build/release
          key: ${{ runner.os }}-proxinject

      - if: steps.cache-proxinject.outputs.cache-hit != true
        uses: actions/checkout@v4
        with:
          repository: PragmaTwice/proxinject
          path: proxinject.build
          fetch-depth: 0

      - if: steps.cache-proxinject.outputs.cache-hit != true
        working-directory: proxinject.build
        run: |
          ./build.ps1 -mode Release -arch x64 # build the project via CMake and msbuild

      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - working-directory: main
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
          pyinstaller --clean mhmp.spec

      - run: |
          mv main/dist/mhmp ./
          mv proxinject.build/release mhmp/
          7z a mhmp-${{ github.ref_name }}-win64.7z ./mhmp/

      - uses: actions/upload-artifact@v4
        with:
          name: mhmp-${{ github.sha }}
          path: mhmp

      - if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT }}
          files: mhmp-${{ github.ref_name }}-win64.7z
